######################################################################
# Automatically generated by qmake (3.0) Mon Dec 30 14:02:51 2013
######################################################################

TEMPLATE = app
TARGET = nicorip
INCLUDEPATH += . src/pugixml
Qt += core
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += src/pugixml/pugiconfig.hpp src/pugixml/pugixml.hpp
SOURCES += src/main.cpp src/ass.cpp src/chapters.cpp src/pugixml/pugixml.cpp
